/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_OE_TSSL_T_H
#define EDGER8R_OE_TSSL_T_H

#include <openenclave/enclave.h>
#include "oe_tssl_args.h"

OE_EXTERNC_BEGIN

/* List of ecalls */

void t_init(void);

OE_EXTERNC_END

#endif // EDGER8R_OE_TSSL_T_H
