/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "oe_tssl_t.h"
#include <openenclave/edger8r/enclave.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN



/****** ECALL function wrappers  *************/
void ecall_t_init(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    t_init_args_t* pargs_in = (t_init_args_t*) input_buffer;
    t_init_args_t* pargs_out = (t_init_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave */
    if (!input_buffer || !oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!output_buffer || !oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* lfence after checks */
    oe_lfence();

    /* Call user function */
    t_init(
        );

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}



/****** ECALL function table  *************/
oe_ecall_func_t __oe_ecalls_table[] = {
    (oe_ecall_func_t) ecall_t_init,
};

size_t __oe_ecalls_table_size = OE_COUNTOF(__oe_ecalls_table);


OE_ECALL void _dummy_old_style_ecall_to_keep_loader_happy(void* arg)
{
    OE_UNUSED(arg);
}

OE_EXTERNC_END
